package com.example.domain.supplychain;

import javax.persistence.*;
import java.util.Date;
import java.util.Set;

@Entity
@Table(name = "RECEIVING_DOCK")
public class ReceivingDockEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, unique = true)
    private String dockNumber;

    @Column(nullable = false)
    private Date receptionDate;

    @OneToMany(mappedBy = "receivingDock", cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch = FetchType.LAZY)
    private Set<ReceivedItemEntity> receivedItems;

    public ReceivingDockEntity() {
        // Default constructor for JPA
    }

    public ReceivingDockEntity(String dockNumber, Date receptionDate) {
        this.dockNumber = dockNumber;
        this.receptionDate = receptionDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDockNumber() {
        return dockNumber;
    }

    public void setDockNumber(String dockNumber) {
        this.dockNumber = dockNumber;
    }

    public Date getReceptionDate() {
        return receptionDate;
    }

    public void setReceptionDate(Date receptionDate) {
        this.receptionDate = receptionDate;
    }

    public Set<ReceivedItemEntity> getReceivedItems() {
        return receivedItems;
    }

    public void setReceivedItems(Set<ReceivedItemEntity> receivedItems) {
        this.receivedItems = receivedItems;
    }
}

### Explanation:

1. **Id and DockNumber**:
   - `id` is the primary key of the entity, generated by the database.
   - `dockNumber` uniquely identifies each receiving dock.

2. **ReceptionDate**:
   - A non-nullable date indicating when the items were received at the dock.

3. **ReceivedItems**:
   - This field represents a many-to-one relationship with `ReceivedItemEntity`, stored as a set to allow multiple items per dock.

4. **Constructors and Getters/Setters**:
   - The constructors provide initialization for new instances.
   - Getters and setters are provided for all fields, facilitating easy access and manipulation of the entity's state.

5. **Fetch Strategy**:
   - `fetch = FetchType.LAZY` ensures that related `ReceivedItemEntity` objects are not eagerly fetched with this entity, optimizing performance by deferring their loading until required.

6. **Cascade Types**:
   - `cascade = {CascadeType.PERSIST, CascadeType.MERGE}` ensures that any changes to the `receivedItems` set will be persisted or merged during save operations on the parent `ReceivingDockEntity`.

This code is designed for a production environment with optimized performance and clear structure.