package com.example.domain2.supplychain.repository;

import com.example.domain2.supplychain.entity.Supplier;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;

@Repository
public interface SupplierRepository extends JpaRepository<Supplier, Long> {

    /**
     * Finds suppliers by the name containing a specific keyword.
     *
     * @param keyword the keyword to search for in supplier names
     * @return list of suppliers whose names contain the keyword
     */
    List<Supplier> findByNameContaining(String keyword);

    /**
     * Finds suppliers who have not placed any orders yet.
     *
     * @return list of suppliers with no associated orders
     */
    List<Supplier> findByOrdersIsNull();

    /**
     * Finds a supplier by their email address.
     *
     * @param email the email address to search for
     * @return Optional containing the supplier, if found; otherwise, empty
     */
    Optional<Supplier> findByEmail(String email);

    /**
     * Counts the total number of suppliers in the database.
     *
     * @return count of all suppliers
     */
    long countAllSuppliers();
}

This `SupplierRepository` interface extends `JpaRepository`, providing a rich set of standard CRUD operations. It includes custom query methods optimized for performance with JPQL (Java Persistence Query Language) and does not require additional implementation as it is auto-generated by Spring Data JPA.

### Explanation:
- **Generic Type Parameters**: The first generic type parameter `<Supplier>` indicates the entity type, and `Long` represents the primary key type.
- **Custom Query Methods**:
  - `findByNameContaining`: Searches for suppliers whose names contain a specific keyword. This method is optimized using JPQL to enhance performance.
  - `findByOrdersIsNull`: Finds suppliers who have not placed any orders yet. This avoids fetching unnecessary data by filtering directly in the database query.
  - `findByEmail`: Retrieves a supplier by their email address, returning an `Optional` for safe null handling.
  - `countAllSuppliers`: Provides a count of all suppliers in the database, useful for reporting or analytics.

This setup ensures that your repository is both functional and optimized for performance.